### PR TITLE
fix: resolve 14 remaining bugs (#17–#31)

### LINKED ISSUE #17: puckToCanonical strips 'format' and other config fields on Publish
## Summary

`buildWidgetDefinition()` in `packages/designer/src/adapters/puck-canonical.ts` uses a `configKeys` whitelist to transfer Puck props → canonical widget config. **`format` is missing from that whitelist**, so publishing from the designer silently drops `format`, `valueField`, `comparisonField`, and `columns` from widget configs.

## Repro

1. Open the vite-sqlite example (fresh localStorage)
2. Switch to Designer mode
3. Click **Publish**
4. Switch to Viewer mode
5. **All KPIs show "—" dashes** instead of values

## Root Cause

`configKeys` array in `puck-canonical.ts:296` is missing `format`. After the round-trip through canonicalToPuck → edit → puckToCanonical, `format: "currency"` and `format: "compact"` are stripped.

The `valueField` and `comparisonField` keys are actually saved via the `The `valueField` and `comparisonField` keys are actualldoThe `valueField` and `comparisonFldThe `valueField` and `comparisonField` keys are actually saved via the `The `vafoThe `, both the ruThe `valueField` ansplThe `valueField` and `comparisonField` keys are actually saved via the `The `valueField` and `comparisonField` keys are actualldoThe `valueField` and `comparisonFldThe `valueField` and `comparisonField` keys are actually saved via the `The `vafoThe `, both the ruThe `valueField` ansplThe `valueField` and `comparisonField` keys afigKeys` whitThe `valueField` and `comparisonField` keys are actacThe `valueField` and `coersThe `valueField` a` (line ~296)

### PR DESCRIPTION
**Pull request by kokokenada**
## Summary

Fixes all 14 remaining open bugs in a single batch.

| Issue | Title | Fix |
|-------|-------|-----|
| #17 | `format` config stripped on Publish | Add `format` to `configKeys` whitelist in puck-canonical adapter |
| #18 | dataBinding fields not translated to widget config | Map field binding roles → config keys in `LayoutRenderer.renderWidget` |
| #19 | KPI prefix config bleed (\$ on Orders) | Remove hardcoded \$prefix from KPI defaults; add prefix/suffix/format in `buildWidgetConfig` |
| #21 | Table preview shows "No data available" | Fall back to sample data when host returns empty array |
| #22 | FIXTURE_VERSION doesn't protect against corruption | Validate stored dashboard structure on localStorage load |
| #23 | ECharts disposed warnings | Memoize wrapped widget components in vite-sqlite registry cache |
| #24 | Comparison query ignores filters | Apply region/category filters to comparison SQL |
| #25 | Sanke| #25 | Sanke| #25 | Sanke| #25 | Sanke| #25 | Sanke| #pt| #25 | Sanke| # #26 || #25 | Sanke| #25 | Sanke| #25 | Sanke| #25 | SorBou| #25 | Sanke| #25 | St |
| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #ote in| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| comp| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #ote in| #27 r o| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular - `| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | Circular layou| #27 | eW| #et.tsx` — NaN guard
- `packages/runtime/src/layout/LayoutRenderer.tsx` — error boundary, cyc- `packages/runtime/src/layout/LayoutRenderer.tsx` — error boundary, cyc- `packagesngine.tsx` — deep equality
- `packages/runtime/src/interactions/DrillManager.tsx` — smart labels
- `packages/designer/src/adapters/puck-canonical.ts` — format key
- `packages/designer/src/preview/ChartPreview.tsx` — KPI defaults, prefix/suffix/format, empty data fallback
- `examples/vite-sqlite/src/App.tsx` — registry memoization, FIXTURE_VERSION validation
- `examples/vite-sqlite/src/sqlite.ts` — comparison query filters

## Verification

- All 1,215 tests pass (`pnpm test`)
- Typecheck clean (`pnpm typecheck` — 12 pre-existing story file errors only)

Closes #17, #18, #19, #21, #22, #23, #24, #25, #26, #27, #28, #29, #30, #31

### CODE REVIEW

File: examples/vite-sqlite/src/sqlite.ts [hunk 1]
```diff
@@ -173,16 +173,30 @@ export async function runAnalyticsQueries(filters: Record<string, unknown>): Pro
     `,
   );
 
+  // Build comparison WHERE clause: apply same region/category filters but use a fixed date range
+  const comparisonConditions: string[] = ["ordered_at < '2026-04-01'"];
```
Comment (kokokenada) [inline examples/vite-sqlite/src/sqlite.ts]: How does a hard coded date make sense? Are these defaults or something?
